src/bin/diffman-git, man/man1/diffman-git.1: Add support for the option terminator '--'
Currently, it's useless, but it will help add path arguments after it.

Signed-off-by: Alejandro Colomar <alx@kernel.org>

diff --git a/src/bin/diffman-git b/src/bin/diffman-git
--- a/src/bin/diffman-git
+++ b/src/bin/diffman-git
@@ -22,7 +22,27 @@ while getopts "sU:w" opt; do
 done;
 shift $((OPTIND-1));
 
-if test $# -gt 2; then
+n=0;
+if test $# -ge 1 && test $1 != '--'; then
+	commit1="$1^";
+	commit2="$1";
+	n=1;
+	shift;
+fi;
+if test $# -ge 1 && test $1 != '--'; then
+	commit1="$commit2";
+	commit2="$1";
+	n=2;
+	shift;
+fi;
+if test $# -ge 1; then
+	if test $1 != '--'; then
+		>&2 echo "$(basename "$0"): error: Too many arguments.";
+		exit 1;
+	fi;
+	shift;
+fi;
+if test $# -ge 1; then
 	>&2 echo "$(basename "$0"): error: Too many arguments.";
 	exit 1;
 fi;
@@ -36,21 +56,19 @@ test -v MANROFFOPT          || export MANROFFOPT='-d AD=l';
 # shellcheck disable=SC2206  # We want only non-empty variables in the array.
 opts=($s $w $u);
 
-case $# in
-0)  git diff --name-only;		;;
-1)  git diff --name-only "$1^..$1";	;;
-*)  git diff --name-only "$1..$2";	;;
+case $n in
+0)  git diff --name-only;			;;
+*)  git diff --name-only "$commit1..$commit2";	;;
 esac \
 | grep -E '(\.[[:digit:]]([[:alpha:]][[:alnum:]]*)?\>|\.man)+(\.man|\.in)*$' \
 | sortman \
 | while read -r f; do \
-	case $# in
-	0)  old="HEAD:$f";  new="./$f";   ;;
-	1)  old="$1^:$f";   new="$1:$f";  ;;
-	*)  old="$1:$f";    new="$2:$f";  ;;
+	case $n in
+	0)  old="HEAD:$f";      new="./$f";         ;;
+	*)  old="$commit1:$f";  new="$commit2:$f";  ;;
 	esac;
 
-	case $# in
+	case $n in
 	0)  cat "$new";       ;;
 	*)  git show "$new";  ;;
 	esac \
